!> \brief subprograms of general use
!> \author Alin M. Elena (Queen's University Belfast) 
!> \date 14-15th of January, 2006



module useful
  use constants
  use types
  
  implicit none
  private
  public :: cstr,error,get_unit
  
contains

!> \brief logical function compares two strings 
!> \details not case sensitive returns true if the strings are the same false otherwise
!> \author Alin M. Elena (Queen's University Belfast) 
!> \date 14-15th of January, 2006
!> \param str1, str2 character(len=*) that get compared 
 
  logical function cstr(str1,str2)
    character(len=*), parameter :: myname = 'cstr'
    character(len=*) :: str1, str2
    integer :: len1,len2,i,s

    len1=len(str1)
    len2=len(str2)
    cstr=.false.
    if (len1==len2) then
      s=0
      do i=1,len1
        s=s+abs(up(str1(i:i))-up(str2(i:i)))
      enddo
      if (s==0) cstr=.true.
    endif
  end function cstr
  
!> \brief integer function returns the ascii code of a letter
!> \details always will be the ascii code of the capital letter
!> as long as the characters are grouped in the set consecutive it should work
!> (A-Z a-z)
!> \author Alin M. Elena (Queen's University Belfast) 
!> \date 14-15th of January, 2006
!> \param a character
  
    integer function up(a)
      character(len=1) :: a
      if (iachar(a)>iachar("Z")) then
        up=iachar(a)-(iachar("a")-iachar("A"))
      else
        up=iachar(a)
      endif
    end function up

!> \brief prints an error/warning message and aborts the programs if necessary
!> \author Alin M. Elena (Queen's University Belfast)
!> \date 14-15th January 2006  
!> \param message the message that will be displayed
!> \param routine the name of the caller
!> \param io_loc I/O details
!> \param critical logical if true aborts the program
!> \remarks  20th of January, 2007, by Alin M Elena (Queen's University Belfast), added io_loc parameter

! provides an elegant way of handling different errors
  subroutine error(message, routine, critical,io_loc)
    character(len=*), intent(in) :: message
    character(len=*), intent(in) :: routine
    logical, intent(in)   :: critical
    type(io_type), intent(in) :: io_loc
    
    if (critical) then
      write(io_loc%uout,*) &
        "Critical error in subroutine: ", routine
    else
      write(io_loc%uout,*) &
        "Error message from subroutine: ", routine
    end if
    
    write(io_loc%uout,*) routine,": ", message
    
    if (critical) then
      write(io_loc%uout,*)routine,": User stop."
      write(*,*)routine," User stop."
      stop
    endif
    
  end subroutine error


!****f*   useful/get_unit()
! NAME
! get_unit
! SYNOPSIS
! get_unit()
! DESCRIPTION
! gives you an integer that you can use as unit to open a file assures that the integer was not previous generated by the function
! USES
! AUTHOR
! Alin M. Elena (Queen's University Belfast)
! CREATION DATE
! 14-15th of January, 2006
! HISTORY
!******

!> \brief gives an integer that can be used as a unit number in a open command
!> \details this function should be used to avoid using the same unit in different open commands
!> \author Alin M Elena 
!> \date 14-15th of January, 2006
!> \warning using a save attribute makes the function thread unsafe, however
!> I do not expect any problems from it (you do not open so many files after all)
  integer function get_unit()
    character(len=*), parameter :: myname = 'get_unit()'
    integer,save ::ustart=9

    ustart=ustart+1
    get_unit=ustart

  end function get_unit

end module useful

